# Generated by Django 4.0.4 on 2022-04-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('numdays', models.PositiveIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.city')),
                ('dayevents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dayevent')),
            ],
        ),
    ]
