# Generated by Django 4.0.4 on 2022-04-29 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dayevent_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayevent',
            name='event',
        ),
        migrations.AddField(
            model_name='dayevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
            preserve_default=False,
        ),
    ]
