# Generated by Django 4.0.4 on 2022-04-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dayevent_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='dayevents',
        ),
        migrations.AddField(
            model_name='dayevent',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.schedule'),
            preserve_default=False,
        ),
    ]
