# Generated by Django 4.0.4 on 2022-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_dayevent_event_dayevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=100),
            preserve_default=False,
        ),
    ]
