# Generated by Django 4.0.4 on 2022-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event_lat_event_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='long',
            field=models.DecimalField(decimal_places=20, max_digits=100),
        ),
    ]
