# Generated by Django 4.0.4 on 2022-04-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_event_city_event_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='neightborhood',
            new_name='neighborhood',
        ),
    ]
