# Generated by Django 4.0.4 on 2022-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_event_lat_alter_event_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='long',
            field=models.FloatField(),
        ),
    ]
